### ISSUE TITLE
Accepting both local and internet files for pi uploading

### ISSUE THREAD

**Issue by PederSkaaravik** [timberline-secondary/hackerspace-scripts#4]
to add the option to use local files from a directory instead of only using an image link.

**Comment by tylerecouture** [comment]
thoughts: 
1. Ask for either location or url (link)
1. Check to see if entry is a link (easiest way is to check for http at the beginning? https://stackoverflow.com/questions/33222909/check-argument-passed-to-a-shell-script-is-an-url
1. if is link, to what already do
1. else, transfer the file using scp or whatever.

**Comment by PederSkaaravik** [comment]
working on it right now, i think im about done! expect a push by tonight.
